#!/usr/bin/env python3
"""Generate src/core/python-unicode.ts: CPython's str.isprintable() tables.

`repr()` escapes every character for which `str.isprintable()` is False, and that depends on
the Unicode database of the Python running Odoo: 3.12 = Unicode 15.0, 3.13 = 15.1, 3.14 = 16.0
(Odoo 20 supports 3.12 to 3.14). The gateway reproduces the repr with the Python 3.12 table and
replaces characters assigned after Unicode 15.0 (printable only on newer Pythons) before signing,
so the webhook signature is identical whatever Python Odoo runs.

Run with Python 3.12 and point PY_NEWEST at the newest supported interpreter:

    PY_NEWEST=~/.pyenv/versions/3.14.3/bin/python3.14 python3.12 scripts/gen_python_unicode.py > src/core/python-unicode.ts
"""
import json
import os
import subprocess
import sys
import unicodedata

DUMP = "import json,sys,unicodedata; print(json.dumps({'version': unicodedata.unidata_version, 'python': sys.version.split()[0], 'np': [c for c in range(0x110000) if not chr(c).isprintable()]}))"


def ranges(codepoints):
    out, start, prev = [], None, None
    for cp in sorted(codepoints):
        if start is None:
            start = prev = cp
        elif cp == prev + 1:
            prev = cp
        else:
            out.append((start, prev))
            start = prev = cp
    if start is not None:
        out.append((start, prev))
    return out


def flat(pairs):
    return ", ".join(f"0x{a:x}, 0x{b:x}" for a, b in pairs)


def main():
    if sys.version_info[:2] != (3, 12):
        sys.exit("run this script with Python 3.12 (Odoo 20's minimum version)")
    base = {c for c in range(0x110000) if not chr(c).isprintable()}
    newest_python = os.environ.get("PY_NEWEST")
    if not newest_python:
        sys.exit("set PY_NEWEST to the newest supported Python (3.14)")
    newest = json.loads(subprocess.check_output([os.path.expanduser(newest_python), "-c", DUMP]))
    newer_printable = base - set(newest["np"])
    became_non_printable = set(newest["np"]) - base
    if became_non_printable:
        sys.exit(f"unexpected: {len(became_non_printable)} code points became non-printable")

    base_ranges = ranges(base)
    newer_ranges = ranges(newer_printable)
    print(f"""// Generated by scripts/gen_python_unicode.py -- do not edit.
// Python {sys.version.split()[0]} (Unicode {unicodedata.unidata_version}) and Python {newest['python']} (Unicode {newest['version']}).

/** Inclusive [start, end] pairs of code points for which Python 3.12 `str.isprintable()` is False. */
export const PY312_NON_PRINTABLE: readonly number[] = [{flat(base_ranges)}];

/** Code points non-printable on Python 3.12 but printable on Python {newest['python']} (assigned after Unicode 15.0). */
export const NEWER_PYTHON_PRINTABLE: readonly number[] = [{flat(newer_ranges)}];

export const PYTHON_UNICODE_VERSIONS = {{ base: "{unicodedata.unidata_version}", newest: "{newest['version']}" }} as const;""")


if __name__ == "__main__":
    main()
