/**
 * Rewrites the `options` table in README.md from the adapters' declarations
 * (`npm run docs:options`). test/unit/options.test.ts fails while the table is stale.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";

import { OPTION_DECLARATIONS } from "../src/providers/index.js";
import { renderOptionsTable } from "../src/providers/options.js";

export const README = new URL("../README.md", import.meta.url);
export const BEGIN = "<!-- options-table:begin (generated by `npm run docs:options`) -->";
export const END = "<!-- options-table:end -->";

/** README text with the generated table between the markers. */
export function withOptionsTable(readme: string): string {
  const start = readme.indexOf(BEGIN);
  const end = readme.indexOf(END);
  if (start < 0 || end < start) throw new Error("README.md has no options-table markers");
  return `${readme.slice(0, start + BEGIN.length)}\n${renderOptionsTable(OPTION_DECLARATIONS)}\n${readme.slice(end)}`;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  writeFileSync(README, withOptionsTable(readFileSync(README, "utf8")));
}
