import { describe, expect, it } from "vitest";

import vectorsFile from "../fixtures/signature-vectors.json" with { type: "json" };
import { PyTuple, printabilityVaries, pyFloatRepr, pyRepr, pyStrRepr } from "../../src/core/pyrepr.js";
import { WEBHOOK_SCOPE, buildWebhookBody, odooHmac, sanitizeForOdoo, sanitizeString, verifyWebhookBody } from "../../src/core/signature.js";

interface Vector {
  name: string;
  secret: string;
  request_uuid: string;
  llm_result_json: string;
  llm_error_json: string;
  python_repr: string;
  signature: string;
}

const vectors = vectorsFile.vectors as Vector[];

describe("signature vectors generated by odoo.tools.misc.hmac", () => {
  it("were produced with Odoo's own implementation", () => {
    expect(vectorsFile.scope).toBe(WEBHOOK_SCOPE);
    expect(vectors.length).toBeGreaterThan(10);
  });

  for (const v of vectors) {
    describe(v.name, () => {
      const llmResult = JSON.parse(v.llm_result_json);
      const llmError = JSON.parse(v.llm_error_json);

      it("uses canonical JSON (what the gateway would actually send)", () => {
        expect(JSON.stringify(llmResult)).toBe(v.llm_result_json);
        expect(JSON.stringify(llmError)).toBe(v.llm_error_json);
      });

      it("reproduces Python's repr()", () => {
        expect(pyRepr(new PyTuple(WEBHOOK_SCOPE, new PyTuple(v.request_uuid, llmResult, llmError)))).toBe(v.python_repr);
      });

      it("reproduces the HMAC-SHA256 signature", () => {
        expect(odooHmac(v.secret, WEBHOOK_SCOPE, new PyTuple(v.request_uuid, llmResult, llmError))).toBe(v.signature);
        const body = buildWebhookBody(v.secret, v.request_uuid, llmResult, llmError);
        if (JSON.stringify(sanitizeForOdoo([llmResult, llmError])) === JSON.stringify([llmResult, llmError])) {
          expect(body.signature).toBe(v.signature);
        } else {
          // NUL is replaced before sending (PostgreSQL jsonb rejects it); the body still verifies.
          expect(body.signature).not.toBe(v.signature);
          expect(verifyWebhookBody(v.secret, body)).toBe(true);
        }
      });

      it("accepts the valid signature", () => {
        expect(
          verifyWebhookBody(v.secret, { request_uuid: v.request_uuid, llm_result: llmResult, llm_error: llmError, signature: v.signature }),
        ).toBe(true);
      });
    });
  }
});

interface SanitizeVector {
  name: string;
  secret: string;
  request_uuid: string;
  raw_llm_result_json: string;
  sent_llm_result_json: string;
  python_repr: string;
  signature: string;
}

describe("payload sanitizing: one signature for every Python Odoo 20 supports", () => {
  it("vectors were cross-checked on Python 3.12 and 3.14", () => {
    expect(vectorsFile.verified_with).toEqual(expect.arrayContaining([expect.stringMatching(/^3\.12\./), expect.stringMatching(/^3\.14\./)]));
  });

  for (const v of vectorsFile.sanitize_vectors as SanitizeVector[]) {
    it(v.name, () => {
      const raw = JSON.parse(v.raw_llm_result_json);
      const body = buildWebhookBody(v.secret, v.request_uuid, raw, false);
      expect(body.llm_result).toEqual(JSON.parse(v.sent_llm_result_json));
      expect(JSON.stringify(body.llm_result)).toBe(v.sent_llm_result_json);
      expect(pyRepr(new PyTuple(WEBHOOK_SCOPE, new PyTuple(v.request_uuid, body.llm_result, false)))).toBe(v.python_repr);
      expect(body.signature).toBe(v.signature);
      expect(verifyWebhookBody(v.secret, body)).toBe(true);
    });
  }

  it("uses Python 3.12's Unicode 15.0 table, not the JavaScript engine's", () => {
    expect(pyStrRepr(String.fromCodePoint(0x1fae9))).toBe("'\\U0001fae9'"); // Unicode 16: Cn for Python 3.12
    expect(pyStrRepr(String.fromCodePoint(0x1f389))).toBe("'\u{1F389}'"); // Unicode 6: printable everywhere
    expect(printabilityVaries(0x1fae9)).toBe(true);
    expect(printabilityVaries(0x2ebf0)).toBe(true);
    expect(printabilityVaries(0x1f389)).toBe(false);
    expect(printabilityVaries(0x0378)).toBe(false); // unassigned everywhere: escaped by every Python
    expect(sanitizeString("plain ascii")).toBe("plain ascii");
  });
});

describe("invalid signatures", () => {
  const v = vectors.find((x) => x.name === "tool_call")!;
  const llmResult = JSON.parse(v.llm_result_json);
  const body = { request_uuid: v.request_uuid, llm_result: llmResult, llm_error: false, signature: v.signature };

  it("rejects a wrong secret", () => {
    expect(verifyWebhookBody("another-secret", body)).toBe(false);
  });

  it("rejects a tampered result", () => {
    const tampered = structuredClone(llmResult);
    tampered.result.content[0].args.limit = 11;
    expect(verifyWebhookBody(v.secret, { ...body, llm_result: tampered })).toBe(false);
  });

  it("rejects an int/float change that JSON would preserve (10 vs 10.5)", () => {
    const tampered = structuredClone(llmResult);
    tampered.result.content[0].args.ratio = 0.50000001;
    expect(verifyWebhookBody(v.secret, { ...body, llm_result: tampered })).toBe(false);
  });

  it("rejects another request_uuid", () => {
    expect(verifyWebhookBody(v.secret, { ...body, request_uuid: "other" })).toBe(false);
  });

  it("rejects a changed llm_error", () => {
    expect(verifyWebhookBody(v.secret, { ...body, llm_error: null })).toBe(false);
  });

  it("rejects a missing or truncated signature", () => {
    expect(verifyWebhookBody(v.secret, { ...body, signature: "" })).toBe(false);
    expect(verifyWebhookBody(v.secret, { ...body, signature: v.signature.slice(0, 32) })).toBe(false);
    expect(verifyWebhookBody(v.secret, { ...body, signature: v.signature.toUpperCase() })).toBe(false);
  });

  it("differs when a key order changes (dict order is part of repr)", () => {
    const reordered = { llm: 1, a: 2 };
    const original = { a: 2, llm: 1 };
    expect(odooHmac("k", WEBHOOK_SCOPE, reordered)).not.toBe(odooHmac("k", WEBHOOK_SCOPE, original));
  });
});

describe("pyRepr details", () => {
  it("formats floats like CPython", () => {
    const cases: Array<[number, string]> = [
      [0.1, "0.1"], [1.5, "1.5"], [-0.5, "-0.5"], [1e-4, "0.0001"], [1e-5, "1e-05"], [1e-7, "1e-07"],
      [1e16, "1e+16"], [1e15, "1000000000000000.0"], [1.5e300, "1.5e+300"], [123.456, "123.456"],
      [2.5e-8, "2.5e-08"], [1e21, "1e+21"], [0, "0.0"], [-0, "-0.0"], [100, "100.0"], [5e-324, "5e-324"],
      [1.7976931348623157e308, "1.7976931348623157e+308"], [123456789.125, "123456789.125"],
    ];
    for (const [value, expected] of cases) expect(pyFloatRepr(value)).toBe(expected);
  });

  it("maps JSON numbers to int or float like json.loads", () => {
    expect(pyRepr(3)).toBe("3");
    expect(pyRepr(-0)).toBe("0");
    expect(pyRepr(3.25)).toBe("3.25");
    expect(pyRepr(1e20)).toBe("100000000000000000000");
    expect(pyRepr(1e21)).toBe("1e+21");
    expect(pyRepr(Number.NaN)).toBe("None");
  });

  it("chooses quotes like CPython", () => {
    expect(pyStrRepr("plain")).toBe("'plain'");
    expect(pyStrRepr("it's")).toBe(`"it's"`);
    expect(pyStrRepr(`say "hi"`)).toBe(`'say "hi"'`);
    expect(pyStrRepr(`both ' and "`)).toBe(`'both \\' and "'`);
    expect(pyStrRepr("\b\f\v")).toBe("'\\x08\\x0c\\x0b'");
  });

  it("formats tuples", () => {
    expect(pyRepr(new PyTuple())).toBe("()");
    expect(pyRepr(new PyTuple(1))).toBe("(1,)");
    expect(pyRepr(new PyTuple("a", false, null))).toBe("('a', False, None)");
  });
});
